-- Auto-generated NFL Analytics Database Schema (Improved)
-- Generated with proper data types for numeric and date columns

-- TEAMS TABLE
CREATE TABLE IF NOT EXISTS teams (
    team_abbr TEXT,
    team_name TEXT,
    team_id TEXT,
    team_nick TEXT,
    team_conf TEXT,
    team_division TEXT,
    team_color TEXT,
    team_color2 TEXT,
    team_color3 TEXT,
    team_color4 TEXT,
    team_logo_wikipedia TEXT,
    team_logo_espn TEXT,
    team_wordmark TEXT,
    team_conference_logo TEXT,
    team_league_logo TEXT,
    team_logo_squared TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (team_abbr)
);

-- PLAYERS TABLE
CREATE TABLE IF NOT EXISTS players (
    college_conference TEXT,
    college_name TEXT,
    current_team_id TEXT,
    display_name TEXT,
    draft_club TEXT,
    draft_number INTEGER,
    draftround REAL,
    entry_year INTEGER,
    esb_id TEXT,
    first_name TEXT,
    football_name TEXT,
    gsis_id TEXT,
    gsis_it_id TEXT,
    jersey_number INTEGER,
    last_name TEXT,
    position TEXT,
    position_group TEXT,
    rookie_year INTEGER,
    short_name TEXT,
    status TEXT,
    status_description_abbr TEXT,
    status_short_description TEXT,
    team_abbr TEXT,
    uniform_number TEXT,
    height TEXT,
    weight INTEGER,
    headshot TEXT,
    smart_id TEXT,
    years_of_experience TEXT,
    birth_date DATE,
    team_seq REAL,
    suffix TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (gsis_id)
);

-- SCHEDULES TABLE
CREATE TABLE IF NOT EXISTS schedules (
    game_id TEXT,
    season INTEGER,
    game_type TEXT,
    week INTEGER,
    gameday DATE,
    weekday TEXT,
    gametime TIME,
    away_team TEXT,
    away_score INTEGER,
    home_team TEXT,
    home_score INTEGER,
    location TEXT,
    result INTEGER,
    total INTEGER,
    overtime BOOLEAN,
    old_game_id TEXT,
    gsis REAL,
    nfl_detail_id TEXT,
    pfr TEXT,
    pff REAL,
    espn REAL,
    ftn REAL,
    away_rest INTEGER,
    home_rest INTEGER,
    away_moneyline INTEGER,
    home_moneyline INTEGER,
    spread_line REAL,
    away_spread_odds INTEGER,
    home_spread_odds INTEGER,
    total_line REAL,
    under_odds INTEGER,
    over_odds INTEGER,
    div_game BOOLEAN,
    roof TEXT,
    surface TEXT,
    temp INTEGER,
    wind INTEGER,
    away_qb_id TEXT,
    home_qb_id TEXT,
    away_qb_name TEXT,
    home_qb_name TEXT,
    away_coach TEXT,
    home_coach TEXT,
    referee TEXT,
    stadium_id TEXT,
    stadium TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (game_id)
);

-- WEEKLY_STATS TABLE
CREATE TABLE IF NOT EXISTS weekly_stats (
    player_id TEXT,
    player_name TEXT,
    player_display_name TEXT,
    position TEXT,
    position_group TEXT,
    headshot_url TEXT,
    recent_team TEXT,
    season INTEGER,
    week INTEGER,
    season_type TEXT,
    opponent_team TEXT,
    completions INTEGER,
    attempts INTEGER,
    passing_yards REAL,
    passing_tds INTEGER,
    interceptions REAL,
    sacks REAL,
    sack_yards REAL,
    sack_fumbles INTEGER,
    sack_fumbles_lost INTEGER,
    passing_air_yards REAL,
    passing_yards_after_catch REAL,
    passing_first_downs REAL,
    passing_epa REAL,
    passing_2pt_conversions INTEGER,
    pacr REAL,
    dakota REAL,
    carries INTEGER,
    rushing_yards REAL,
    rushing_tds INTEGER,
    rushing_fumbles REAL,
    rushing_fumbles_lost REAL,
    rushing_first_downs REAL,
    rushing_epa REAL,
    rushing_2pt_conversions INTEGER,
    receptions INTEGER,
    targets INTEGER,
    receiving_yards REAL,
    receiving_tds INTEGER,
    receiving_fumbles REAL,
    receiving_fumbles_lost REAL,
    receiving_air_yards REAL,
    receiving_yards_after_catch REAL,
    receiving_first_downs REAL,
    receiving_epa REAL,
    receiving_2pt_conversions INTEGER,
    racr REAL,
    target_share REAL,
    air_yards_share REAL,
    wopr REAL,
    special_teams_tds REAL,
    fantasy_points REAL,
    fantasy_points_ppr REAL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (player_id, season, week, season_type)
);

-- SEASONAL_STATS TABLE
CREATE TABLE IF NOT EXISTS seasonal_stats (
    player_id TEXT,
    season INTEGER,
    season_type TEXT,
    completions INTEGER,
    attempts INTEGER,
    passing_yards REAL,
    passing_tds INTEGER,
    interceptions REAL,
    sacks REAL,
    sack_yards REAL,
    sack_fumbles INTEGER,
    sack_fumbles_lost INTEGER,
    passing_air_yards REAL,
    passing_yards_after_catch REAL,
    passing_first_downs REAL,
    passing_epa REAL,
    passing_2pt_conversions INTEGER,
    pacr REAL,
    dakota REAL,
    carries INTEGER,
    rushing_yards REAL,
    rushing_tds INTEGER,
    rushing_fumbles REAL,
    rushing_fumbles_lost REAL,
    rushing_first_downs REAL,
    rushing_epa REAL,
    rushing_2pt_conversions INTEGER,
    receptions INTEGER,
    targets INTEGER,
    receiving_yards REAL,
    receiving_tds INTEGER,
    receiving_fumbles REAL,
    receiving_fumbles_lost REAL,
    receiving_air_yards REAL,
    receiving_yards_after_catch REAL,
    receiving_first_downs REAL,
    receiving_epa REAL,
    receiving_2pt_conversions INTEGER,
    racr REAL,
    target_share REAL,
    air_yards_share REAL,
    wopr_x REAL,
    special_teams_tds REAL,
    fantasy_points REAL,
    fantasy_points_ppr REAL,
    games INTEGER,
    tgt_sh REAL,
    ay_sh REAL,
    yac_sh REAL,
    wopr_y REAL,
    ry_sh REAL,
    rtd_sh REAL,
    rfd_sh REAL,
    rtdfd_sh REAL,
    dom REAL,
    w8dom REAL,
    yptmpa REAL,
    ppr_sh REAL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (player_id, season, season_type)
);

-- ROSTERS TABLE
CREATE TABLE IF NOT EXISTS rosters (
    season INTEGER,
    team TEXT,
    position TEXT,
    depth_chart_position TEXT,
    jersey_number INTEGER,
    status TEXT,
    player_name TEXT,
    first_name TEXT,
    last_name TEXT,
    birth_date DATE,
    height TEXT,
    weight INTEGER,
    college TEXT,
    player_id TEXT,
    espn_id TEXT,
    sportradar_id TEXT,
    yahoo_id TEXT,
    rotowire_id TEXT,
    pff_id TEXT,
    pfr_id TEXT,
    fantasy_data_id TEXT,
    sleeper_id TEXT,
    years_exp INTEGER,
    headshot_url TEXT,
    ngs_position TEXT,
    week INTEGER,
    game_type TEXT,
    status_description_abbr TEXT,
    football_name TEXT,
    esb_id TEXT,
    gsis_it_id TEXT,
    smart_id TEXT,
    entry_year INTEGER,
    rookie_year INTEGER,
    draft_club TEXT,
    draft_number INTEGER,
    age REAL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (player_id, season, week, team)
);

-- PBP_DATA TABLE
CREATE TABLE IF NOT EXISTS pbp_data (
    play_id TEXT,
    game_id TEXT,
    old_game_id TEXT,
    home_team TEXT,
    away_team TEXT,
    season_type TEXT,
    week INTEGER,
    posteam TEXT,
    posteam_type TEXT,
    defteam TEXT,
    side_of_field TEXT,
    yardline_100 INTEGER,
    game_date DATE,
    quarter_seconds_remaining INTEGER,
    half_seconds_remaining INTEGER,
    game_seconds_remaining INTEGER,
    game_half TEXT,
    quarter_end BOOLEAN,
    drive INTEGER,
    sp BOOLEAN,
    qtr INTEGER,
    down INTEGER,
    goal_to_go BOOLEAN,
    game_time TEXT,
    yrdln TEXT,
    ydstogo INTEGER,
    ydsnet INTEGER,
    play_description TEXT,
    play_type TEXT,
    yards_gained REAL,
    shotgun BOOLEAN,
    no_huddle BOOLEAN,
    qb_dropback BOOLEAN,
    qb_kneel BOOLEAN,
    qb_spike BOOLEAN,
    qb_scramble BOOLEAN,
    pass_length TEXT,
    pass_location TEXT,
    air_yards REAL,
    yards_after_catch REAL,
    run_location TEXT,
    run_gap TEXT,
    field_goal_result TEXT,
    kick_distance INTEGER,
    extra_point_result TEXT,
    two_point_conv_result TEXT,
    home_timeouts_remaining INTEGER,
    away_timeouts_remaining INTEGER,
    timeout BOOLEAN,
    timeout_team TEXT,
    td_team TEXT,
    td_player_name TEXT,
    td_player_id TEXT,
    posteam_timeouts_remaining INTEGER,
    defteam_timeouts_remaining INTEGER,
    total_home_score INTEGER,
    total_away_score INTEGER,
    posteam_score INTEGER,
    defteam_score INTEGER,
    score_differential INTEGER,
    posteam_score_post INTEGER,
    defteam_score_post INTEGER,
    score_differential_post INTEGER,
    no_score_prob REAL,
    opp_fg_prob REAL,
    opp_safety_prob REAL,
    opp_td_prob REAL,
    fg_prob REAL,
    safety_prob REAL,
    td_prob REAL,
    extra_point_prob REAL,
    two_point_conversion_prob REAL,
    ep REAL,
    epa REAL,
    total_home_epa REAL,
    total_away_epa REAL,
    total_home_rush_epa REAL,
    total_away_rush_epa REAL,
    total_home_pass_epa REAL,
    total_away_pass_epa REAL,
    air_epa REAL,
    yac_epa REAL,
    comp_air_epa REAL,
    comp_yac_epa REAL,
    total_home_comp_air_epa REAL,
    total_away_comp_air_epa REAL,
    total_home_comp_yac_epa REAL,
    total_away_comp_yac_epa REAL,
    total_home_raw_air_epa REAL,
    total_away_raw_air_epa REAL,
    total_home_raw_yac_epa REAL,
    total_away_raw_yac_epa REAL,
    wp REAL,
    def_wp REAL,
    home_wp REAL,
    away_wp REAL,
    wpa REAL,
    vegas_wpa REAL,
    vegas_home_wpa REAL,
    home_wp_post REAL,
    away_wp_post REAL,
    vegas_wp REAL,
    vegas_home_wp REAL,
    total_home_rush_wpa REAL,
    total_away_rush_wpa REAL,
    total_home_pass_wpa REAL,
    total_away_pass_wpa REAL,
    air_wpa REAL,
    yac_wpa REAL,
    comp_air_wpa REAL,
    comp_yac_wpa REAL,
    total_home_comp_air_wpa REAL,
    total_away_comp_air_wpa REAL,
    total_home_comp_yac_wpa REAL,
    total_away_comp_yac_wpa REAL,
    total_home_raw_air_wpa REAL,
    total_away_raw_air_wpa REAL,
    total_home_raw_yac_wpa REAL,
    total_away_raw_yac_wpa REAL,
    punt_blocked BOOLEAN,
    first_down_rush BOOLEAN,
    first_down_pass BOOLEAN,
    first_down_penalty BOOLEAN,
    third_down_converted BOOLEAN,
    third_down_failed BOOLEAN,
    fourth_down_converted BOOLEAN,
    fourth_down_failed BOOLEAN,
    incomplete_pass BOOLEAN,
    touchback BOOLEAN,
    interception BOOLEAN,
    punt_inside_twenty REAL,
    punt_in_endzone REAL,
    punt_out_of_bounds REAL,
    punt_downed REAL,
    punt_fair_catch REAL,
    kickoff_inside_twenty REAL,
    kickoff_in_endzone REAL,
    kickoff_out_of_bounds REAL,
    kickoff_downed REAL,
    kickoff_fair_catch REAL,
    fumble_forced REAL,
    fumble_not_forced REAL,
    fumble_out_of_bounds BOOLEAN,
    solo_tackle REAL,
    safety REAL,
    penalty REAL,
    tackled_for_loss REAL,
    fumble_lost REAL,
    own_kickoff_recovery REAL,
    own_kickoff_recovery_td REAL,
    qb_hit REAL,
    rush_attempt REAL,
    pass_attempt REAL,
    sack REAL,
    touchdown REAL,
    pass_touchdown REAL,
    rush_touchdown REAL,
    return_touchdown REAL,
    extra_point_attempt REAL,
    two_point_attempt REAL,
    field_goal_attempt REAL,
    kickoff_attempt REAL,
    punt_attempt REAL,
    fumble BOOLEAN,
    complete_pass BOOLEAN,
    assist_tackle BOOLEAN,
    lateral_reception BOOLEAN,
    lateral_rush BOOLEAN,
    lateral_return BOOLEAN,
    lateral_recovery BOOLEAN,
    passer_player_id TEXT,
    passer_player_name TEXT,
    passing_yards REAL,
    receiver_player_id TEXT,
    receiver_player_name TEXT,
    receiving_yards REAL,
    rusher_player_id TEXT,
    rusher_player_name TEXT,
    rushing_yards REAL,
    lateral_receiver_player_id TEXT,
    lateral_receiver_player_name TEXT,
    lateral_receiving_yards REAL,
    lateral_rusher_player_id TEXT,
    lateral_rusher_player_name TEXT,
    lateral_rushing_yards REAL,
    lateral_sack_player_id TEXT,
    lateral_sack_player_name TEXT,
    interception_player_id TEXT,
    interception_player_name TEXT,
    lateral_interception_player_id TEXT,
    lateral_interception_player_name TEXT,
    punt_returner_player_id TEXT,
    punt_returner_player_name TEXT,
    lateral_punt_returner_player_id TEXT,
    lateral_punt_returner_player_name TEXT,
    kickoff_returner_player_name TEXT,
    kickoff_returner_player_id TEXT,
    lateral_kickoff_returner_player_id TEXT,
    lateral_kickoff_returner_player_name TEXT,
    punter_player_id TEXT,
    punter_player_name TEXT,
    kicker_player_name TEXT,
    kicker_player_id TEXT,
    own_kickoff_recovery_player_id TEXT,
    own_kickoff_recovery_player_name TEXT,
    blocked_player_id TEXT,
    blocked_player_name TEXT,
    tackle_for_loss_1_player_id TEXT,
    tackle_for_loss_1_player_name TEXT,
    tackle_for_loss_2_player_id TEXT,
    tackle_for_loss_2_player_name TEXT,
    qb_hit_1_player_id TEXT,
    qb_hit_1_player_name TEXT,
    qb_hit_2_player_id TEXT,
    qb_hit_2_player_name TEXT,
    forced_fumble_player_1_team TEXT,
    forced_fumble_player_1_player_id TEXT,
    forced_fumble_player_1_player_name TEXT,
    forced_fumble_player_2_team TEXT,
    forced_fumble_player_2_player_id TEXT,
    forced_fumble_player_2_player_name TEXT,
    solo_tackle_1_team TEXT,
    solo_tackle_2_team TEXT,
    solo_tackle_1_player_id TEXT,
    solo_tackle_2_player_id TEXT,
    solo_tackle_1_player_name TEXT,
    solo_tackle_2_player_name TEXT,
    assist_tackle_1_player_id TEXT,
    assist_tackle_1_player_name TEXT,
    assist_tackle_1_team TEXT,
    assist_tackle_2_player_id TEXT,
    assist_tackle_2_player_name TEXT,
    assist_tackle_2_team TEXT,
    assist_tackle_3_player_id TEXT,
    assist_tackle_3_player_name TEXT,
    assist_tackle_3_team TEXT,
    assist_tackle_4_player_id TEXT,
    assist_tackle_4_player_name TEXT,
    assist_tackle_4_team TEXT,
    tackle_with_assist BOOLEAN,
    tackle_with_assist_1_player_id TEXT,
    tackle_with_assist_1_player_name TEXT,
    tackle_with_assist_1_team TEXT,
    tackle_with_assist_2_player_id TEXT,
    tackle_with_assist_2_player_name TEXT,
    tackle_with_assist_2_team TEXT,
    pass_defense_1_player_id TEXT,
    pass_defense_1_player_name TEXT,
    pass_defense_2_player_id TEXT,
    pass_defense_2_player_name TEXT,
    fumbled_1_team TEXT,
    fumbled_1_player_id TEXT,
    fumbled_1_player_name TEXT,
    fumbled_2_player_id TEXT,
    fumbled_2_player_name TEXT,
    fumbled_2_team TEXT,
    fumble_recovery_1_team TEXT,
    fumble_recovery_1_yards REAL,
    fumble_recovery_1_player_id TEXT,
    fumble_recovery_1_player_name TEXT,
    fumble_recovery_2_team TEXT,
    fumble_recovery_2_yards REAL,
    fumble_recovery_2_player_id TEXT,
    fumble_recovery_2_player_name TEXT,
    sack_player_id TEXT,
    sack_player_name TEXT,
    half_sack_1_player_id TEXT,
    half_sack_1_player_name TEXT,
    half_sack_2_player_id TEXT,
    half_sack_2_player_name TEXT,
    return_team TEXT,
    return_yards REAL,
    penalty_team TEXT,
    penalty_player_id TEXT,
    penalty_player_name TEXT,
    penalty_yards REAL,
    replay_or_challenge BOOLEAN,
    replay_or_challenge_result TEXT,
    penalty_type TEXT,
    defensive_two_point_attempt REAL,
    defensive_two_point_conv REAL,
    defensive_extra_point_attempt REAL,
    defensive_extra_point_conv REAL,
    safety_player_name TEXT,
    safety_player_id TEXT,
    season INTEGER,
    cp REAL,
    cpoe REAL,
    series INTEGER,
    series_success BOOLEAN,
    series_result TEXT,
    order_sequence INTEGER,
    start_time TEXT,
    time_of_day TEXT,
    stadium TEXT,
    weather TEXT,
    nfl_api_id TEXT,
    play_clock INTEGER,
    play_deleted REAL,
    play_type_nfl TEXT,
    special_teams_play REAL,
    st_play_type TEXT,
    end_clock_time TEXT,
    end_yard_line TEXT,
    fixed_drive INTEGER,
    fixed_drive_result TEXT,
    drive_real_start_time REAL,
    drive_play_count INTEGER,
    drive_time_of_possession REAL,
    drive_first_downs INTEGER,
    drive_inside20 BOOLEAN,
    drive_ended_with_score BOOLEAN,
    drive_quarter_start INTEGER,
    drive_quarter_end INTEGER,
    drive_yards_penalized INTEGER,
    drive_start_transition TEXT,
    drive_end_transition TEXT,
    drive_game_clock_start TEXT,
    drive_game_clock_end TEXT,
    drive_start_yard_line INTEGER,
    drive_end_yard_line INTEGER,
    drive_play_id_started REAL,
    drive_play_id_ended REAL,
    away_score INTEGER,
    home_score INTEGER,
    location TEXT,
    result INTEGER,
    total INTEGER,
    spread_line REAL,
    total_line REAL,
    div_game BOOLEAN,
    roof TEXT,
    surface TEXT,
    temp INTEGER,
    wind INTEGER,
    home_coach TEXT,
    away_coach TEXT,
    stadium_id TEXT,
    game_stadium TEXT,
    aborted_play REAL,
    success REAL,
    passer TEXT,
    passer_jersey_number REAL,
    rusher TEXT,
    rusher_jersey_number REAL,
    receiver TEXT,
    receiver_jersey_number REAL,
    pass REAL,
    rush REAL,
    first_down BOOLEAN,
    special REAL,
    play REAL,
    passer_id TEXT,
    rusher_id TEXT,
    receiver_id TEXT,
    name TEXT,
    jersey_number INTEGER,
    id TEXT,
    fantasy_player_name TEXT,
    fantasy_player_id TEXT,
    fantasy TEXT,
    fantasy_id TEXT,
    out_of_bounds REAL,
    home_opening_kickoff REAL,
    qb_epa REAL,
    xyac_epa REAL,
    xyac_mean_yardage REAL,
    xyac_median_yardage REAL,
    xyac_success REAL,
    xyac_fd REAL,
    xpass REAL,
    pass_oe REAL,
    nflverse_game_id TEXT,
    possession_team TEXT,
    offense_formation TEXT,
    offense_personnel TEXT,
    defenders_in_box REAL,
    defense_personnel TEXT,
    number_of_pass_rushers REAL,
    players_on_play TEXT,
    offense_players TEXT,
    defense_players TEXT,
    n_offense REAL,
    n_defense REAL,
    ngs_air_yards REAL,
    time_to_throw REAL,
    was_pressure TEXT,
    route TEXT,
    defense_man_zone_type TEXT,
    defense_coverage_type TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (game_id, play_id)
);

-- INJURIES TABLE
CREATE TABLE IF NOT EXISTS injuries (
    season INTEGER,
    game_type TEXT,
    team TEXT,
    week INTEGER,
    gsis_id TEXT,
    position TEXT,
    full_name TEXT,
    first_name TEXT,
    last_name TEXT,
    report_primary_injury TEXT,
    report_secondary_injury TEXT,
    report_status TEXT,
    practice_primary_injury TEXT,
    practice_secondary_injury TEXT,
    practice_status TEXT,
    date_modified TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (season, week)
);

-- DATA_REFRESH_LOG TABLE

            CREATE TABLE IF NOT EXISTS data_refresh_log (
                id INTEGER PRIMARY KEY,
                table_name TEXT NOT NULL,
                season INTEGER NOT NULL,
                week INTEGER,
                season_type TEXT NOT NULL,
                refresh_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                status TEXT NOT NULL CHECK (status IN ('SUCCESS', 'FAILED', 'IN_PROGRESS')),
                error_message TEXT,
                records_processed INTEGER DEFAULT 0
            );
            

-- INDEXES
CREATE INDEX IF NOT EXISTS idx_pbp_game_id ON pbp_data(game_id);
CREATE INDEX IF NOT EXISTS idx_pbp_season_week ON pbp_data(season, week);
CREATE INDEX IF NOT EXISTS idx_pbp_season_type ON pbp_data(season_type);
CREATE INDEX IF NOT EXISTS idx_pbp_posteam ON pbp_data(posteam);
CREATE INDEX IF NOT EXISTS idx_pbp_defteam ON pbp_data(defteam);
CREATE INDEX IF NOT EXISTS idx_pbp_play_type ON pbp_data(play_type);
CREATE INDEX IF NOT EXISTS idx_pbp_down ON pbp_data(down);
CREATE INDEX IF NOT EXISTS idx_pbp_quarter ON pbp_data(qtr);
CREATE INDEX IF NOT EXISTS idx_pbp_game_date ON pbp_data(game_date);
CREATE INDEX IF NOT EXISTS idx_weekly_player_season ON weekly_stats(player_id, season, week);
CREATE INDEX IF NOT EXISTS idx_weekly_season_type ON weekly_stats(season_type);
CREATE INDEX IF NOT EXISTS idx_weekly_position ON weekly_stats(position);
CREATE INDEX IF NOT EXISTS idx_weekly_team ON weekly_stats(recent_team);
CREATE INDEX IF NOT EXISTS idx_weekly_opponent ON weekly_stats(opponent_team);
CREATE INDEX IF NOT EXISTS idx_weekly_fantasy_points ON weekly_stats(fantasy_points);
CREATE INDEX IF NOT EXISTS idx_seasonal_player_season ON seasonal_stats(player_id, season);
CREATE INDEX IF NOT EXISTS idx_seasonal_season_type ON seasonal_stats(season_type);
CREATE INDEX IF NOT EXISTS idx_seasonal_position ON seasonal_stats(position);
CREATE INDEX IF NOT EXISTS idx_seasonal_team ON seasonal_stats(recent_team);
CREATE INDEX IF NOT EXISTS idx_seasonal_fantasy_points ON seasonal_stats(fantasy_points);
CREATE INDEX IF NOT EXISTS idx_schedules_season_week ON schedules(season, week);
CREATE INDEX IF NOT EXISTS idx_schedules_game_date ON schedules(gameday);
CREATE INDEX IF NOT EXISTS idx_schedules_teams ON schedules(home_team, away_team);
CREATE INDEX IF NOT EXISTS idx_schedules_season_type ON schedules(season_type);
CREATE INDEX IF NOT EXISTS idx_rosters_player_season ON rosters(player_id, season, week);
CREATE INDEX IF NOT EXISTS idx_rosters_team ON rosters(team);
CREATE INDEX IF NOT EXISTS idx_rosters_position ON rosters(position);
CREATE INDEX IF NOT EXISTS idx_rosters_status ON rosters(status);
CREATE INDEX IF NOT EXISTS idx_players_position ON players(position);
CREATE INDEX IF NOT EXISTS idx_players_team ON players(team);
CREATE INDEX IF NOT EXISTS idx_players_status ON players(status);
CREATE INDEX IF NOT EXISTS idx_players_college ON players(college);
CREATE INDEX IF NOT EXISTS idx_players_draft_year ON players(entry_year);
CREATE INDEX IF NOT EXISTS idx_teams_conf_div ON teams(team_conf, team_division);
CREATE INDEX IF NOT EXISTS idx_injuries_player_season ON injuries(player_id, season, week);
CREATE INDEX IF NOT EXISTS idx_injuries_report_date ON injuries(report_date);
CREATE INDEX IF NOT EXISTS idx_injuries_status ON injuries(report_status);
CREATE INDEX IF NOT EXISTS idx_refresh_log_table ON data_refresh_log(table_name, season, week);
CREATE INDEX IF NOT EXISTS idx_refresh_log_status ON data_refresh_log(status);
CREATE INDEX IF NOT EXISTS idx_refresh_log_date ON data_refresh_log(refresh_date);
